# Generated by Django 2.2.1 on 2019-05-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='main_title',
            new_name='name',
        ),
    ]
