# Generated by Django 2.2.1 on 2019-05-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190520_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='text',
            new_name='content',
        ),
    ]
