# Generated by Django 2.2.1 on 2019-05-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Abouts',
        ),
    ]
