# Generated by Django 2.2.1 on 2019-05-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20190520_2028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abouts',
            new_name='About',
        ),
    ]
