# Generated by Django 2.2.1 on 2019-05-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190521_0722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Abouts',
        ),
    ]
