# Generated by Django 2.2.1 on 2019-05-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20190521_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
