# Generated by Django 2.2.1 on 2019-05-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20190521_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('background_image', models.ImageField(upload_to='about/')),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Profile')),
            ],
        ),
    ]
