# Generated by Django 2.2.1 on 2019-05-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_post_sub_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='content',
            new_name='sub_title',
        ),
    ]
