# Generated by Django 2.2.1 on 2019-05-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/'),
        ),
    ]
