# Generated by Django 2.2.1 on 2019-05-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_contact_background_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
