# Generated by Django 2.2.1 on 2019-05-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Articles')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Profile')),
            ],
        ),
    ]
