# Generated by Django 2.2.1 on 2019-05-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_authorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorProfile',
        ),
    ]
