# Generated by Django 2.2.1 on 2019-06-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20190602_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='myarticles/')),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
