# Generated by Django 2.2.1 on 2019-06-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_myarticles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyArticles',
        ),
    ]
