# Generated by Django 2.2.1 on 2019-06-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20190624_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='background_image',
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
