# Generated by Django 2.2.1 on 2019-06-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20190624_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='image',
            new_name='background_image',
        ),
    ]
