# Generated by Django 2.2.1 on 2019-06-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20190626_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='background_image',
        ),
    ]
