# Generated by Django 2.2.1 on 2019-06-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_auto_20190627_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='background_image',
            new_name='image',
        ),
    ]
