# Generated by Django 2.2.1 on 2019-06-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_auto_20190627_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='background_image',
        ),
    ]
